import type { Metadata } from "next";
import { Geist, PT_Serif } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSerif = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const ptSerif = PT_Serif({
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
// test

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSerif.variable} antialiased flex flex-row h-screen`}
      >
        <nav className="flex flex-col gap-6 mr-6 py-8 pl-10">
          <div className="gap-4 flex flex-col">
            <Link href="/">
              <h1 className={`text-3xl ${ptSerif.className}`}>
                Kieran Sukachevin
              </h1>
            </Link>
            <Link href="/" className="hover:text-gray-600">
              Art
            </Link>
            <Link href="/about" className="hover:text-gray-600">
              About
            </Link>
          </div>
          <div className="gap-4 flex flex-col">
            <a href="https://www.instagram.com/kieransuka/" target="_blank">
              <Image
                src="logos/instagram.svg"
                alt="Instagram"
                width={25}
                height={25}
              />
            </a>
            <a
              href="https://www.pinterest.com/kieransukachevin/"
              target="_blank"
            >
              <Image
                src="logos/pinterest.svg"
                alt="Pinterest"
                width={20}
                height={20}
              />
            </a>
            <a href="https://www.tumblr.com/kieransukachevin" target="_blank">
              <Image
                src="logos/tumblr.svg"
                alt="Tumblr"
                width={15}
                height={15}
              />
            </a>
          </div>
        </nav>
        <main className="flex-1 overflow-y-auto py-6 pr-10">{children}</main>
      </body>
    </html>
  );
}
