import type { Metadata } from "next";
import { Geist, PT_Serif } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Cart from "./ui/cart";

const geistSerif = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const ptSerif = PT_Serif({
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSerif.variable} antialiased block h-screen`}>
        <nav className="relative md:fixed top-0 left-0 flex flex-col gap-6 pl-10 py-8 w-56 z-[100]">
          <div>
            <Link href="/">
              <h1 className={`text-3xl ${ptSerif.className}`}>
                Kieran
                <br />
                Sukachevin
              </h1>
            </Link>
          </div>
          <div className="gap-4 flex sm:flex-row md:flex-col">
            <Link
              href="/"
              className="hover:text-gray-600 transition-all duration-100 cursor-pointer"
            >
              Art
            </Link>
            <Link
              href="/zines"
              className="hover:text-gray-600 transition-all duration-100 cursor-pointer"
            >
              Zines
            </Link>
            <Link
              href="/about"
              className="hover:text-gray-600 transition-all duration-100 cursor-pointer"
            >
              About
            </Link>
          </div>
          <div className="gap-4 flex sm:flex-row md:flex-col">
            <a href="https://www.instagram.com/kieransuka/" target="_blank">
              <Image
                src="logos/instagram.svg"
                alt="Instagram"
                width={25}
                height={25}
              />
            </a>
            <a
              href="https://www.pinterest.com/kieransukachevin/"
              target="_blank"
            >
              <Image
                src="logos/pinterest.svg"
                alt="Pinterest"
                width={20}
                height={20}
              />
            </a>
            <a href="https://www.tumblr.com/kieransukachevin" target="_blank">
              <Image
                src="logos/tumblr.svg"
                alt="Tumblr"
                width={15}
                height={15}
              />
            </a>
          </div>
        </nav>

        {children}

        <Cart />
      </body>
    </html>
  );
}
